<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #191c1e; margin: 0; padding: 20px; }
        .header { background: #001e40; color: #fff; padding: 20px; text-align: center; border-radius: 8px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 20px; }
        .header p { margin: 4px 0; opacity: 0.8; font-size: 11px; }
        .info-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 20px; }
        .info-box { background: #f2f4f7; padding: 12px; border-radius: 6px; }
        .info-box label { font-size: 9px; font-weight: 700; text-transform: uppercase; color: #43474f; display: block; margin-bottom: 4px; }
        .info-box span { font-weight: 600; color: #001e40; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th { background: #003366; color: #fff; padding: 8px; text-align: left; font-size: 10px; font-weight: 700; }
        td { padding: 6px 8px; border-bottom: 1px solid #e0e3e6; font-size: 10px; }
        .amount { text-align: right; }
        .total-row td { background: #eceef1; font-weight: bold; border-top: 2px solid #003366; }
        .footer { margin-top: 30px; text-align: center; color: #737780; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>AIUB HRMS</h1>
        <p>Payroll Run Summary</p>
        <p>{{ \Carbon\Carbon::createFromDate($payrollRun->year, $payrollRun->month, 1)->format('F Y') }} - {{ $payrollRun->run_code }}</p>
    </div>

    <div class="info-grid">
        <div class="info-box"><label>Status</label><span>{{ strtoupper($payrollRun->status) }}</span></div>
        <div class="info-box"><label>Total Gross</label><span>৳ {{ number_format($payrollRun->total_gross, 2) }}</span></div>
        <div class="info-box"><label>Total Deductions</label><span>৳ {{ number_format($payrollRun->total_deductions, 2) }}</span></div>
        <div class="info-box"><label>Total Net</label><span>৳ {{ number_format($payrollRun->total_net, 2) }}</span></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Emp ID</th>
                <th>Name</th>
                <th>Department</th>
                <th class="amount">Basic (৳)</th>
                <th class="amount">Allowances (৳)</th>
                <th class="amount">Gross (৳)</th>
                <th class="amount">Deductions (৳)</th>
                <th class="amount">Net Pay (৳)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payrollRun->items as $item)
            <tr>
                <td>{{ $item->employee->employee_id }}</td>
                <td>{{ $item->employee->full_name }}</td>
                <td>{{ $item->employee->department->name ?? 'N/A' }}</td>
                <td class="amount">{{ number_format($item->basic_salary, 2) }}</td>
                <td class="amount">{{ number_format($item->gross_salary - $item->basic_salary, 2) }}</td>
                <td class="amount">{{ number_format($item->gross_salary, 2) }}</td>
                <td class="amount">{{ number_format($item->total_deductions, 2) }}</td>
                <td class="amount"><strong>{{ number_format($item->net_salary, 2) }}</strong></td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="5" style="text-align: right;"><strong>Totals</strong></td>
                <td class="amount">{{ number_format($payrollRun->total_gross, 2) }}</td>
                <td class="amount">{{ number_format($payrollRun->total_deductions, 2) }}</td>
                <td class="amount">{{ number_format($payrollRun->total_net, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ $payrollRun->creator->name ?? 'System' }} on {{ now()->format('d M Y H:i') }}
        @if($payrollRun->approved_by)
            <br>Approved by {{ $payrollRun->approver->name }} on {{ $payrollRun->approved_at->format('d M Y H:i') }}
        @endif
    </div>
</body>
</html>
